### ISSUE TITLE
what do the numbers in file "entailment_vocab_200.glove" mean?

### ISSUE THREAD

**Issue by heslowen** [context-mover/context-mover-distance-and-barycenters#1]
For example, the first line" the 111517827 "?

**Comment by sidak** [comment]
Hi @heslowen! 

Let me first apologize for such an enormous delay. This account was started from a separate account instead of my personal one to preserve anonymity, as a result, I didn't receive any notifications. 

This file corresponds to the vocabulary of the input corpus. So each line contains `<token_name> <token_counts>`. You can obtain a similar file based on the corpus that you are using, with the help of this [code](https://github.com/stanfordnlp/GloVe/blob/master/src/vocab_count.c) from GloVe. 

This file is then passed as an input to [coccur.c](https://github.com/stanfordnlp/GloVe/blob/master/src/cooccur.c), while computing the co-occurrence information.
