### ISSUE TITLE
Any description of pretrained data and histograms?

### ISSUE THREAD

**Issue by heslowen** [context-mover/context-mover-distance-and-barycenters#3]
I can not find any description for these files. So if you  are  realy willing to share it on githup, I think some readme.md would be batter. Or you just pretend to share it to get a ICLR paper?
![image](https://user-images.githubusercontent.com/22348625/70211795-e68d0900-1770-11ea-9f3b-23fe2e7972bf.png)

**Comment by sidak** [comment]
The pretrained `ppmi_coocurrence..` files are the histograms for each word over all the contexts in the vocabulary. These are basically stored in numpy arrays stored in the zipped format (`.npz`). You don't have to extract them at all. 

For example, as indicated in the README, just use them like 

```
python histograms.py    --cooc-root-path ./data/cooc/book_coocurrence_symmetric\=1_window-size\=10_cleaned\=300/  \
                        --ppmi-path ./data/cooc/book_coocurrence_symmetric\=1_window-size\=10_cleaned\=300/ppmi_smooth_0.75_k-shift_1.0.npz \
                        --cluster-data-dir ./data/vectors/clusters/book_glove_symmetric=1_window-size=10_min-count=10_eta=0.005_iter=75_cleaned=300/kmeans_100_205513 \
                        --histogram-data-dir ./data/histograms/
```

Lastly, to reiterate what I mentioned on the previous issue, I apologize for this enormous delay. This account was started from a separate account instead of my personal one to preserve anonymity, as a result, I didn't receive any notifications. (You can always send me an email if you have any issues.) Nevertheless, I should have been more pro-active, and hope this is helpful despite the delay. 

Thanks for your interest,
Sidak
